config/routes.rb
Rails.application.routes.draw do
  
  root  'posts#index'
  get   '/:title'               => 'posts#show',         as: 'detailed'
  get   '/categorize/:category' => 'posts#categorize',   as: 'categorize'

  scope '/api' do
    resources :posts, only: [], defaults: { format: 'json' } do
    	collection do
    		get 'search'
    	end
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  def self.get(title)
    title = title.gsub('-', ' ')
    where('LOWER(title) = ?', "#{title}").first
  end


  def self.search(keyword)
    where('title ILIKE ?', "%#{keyword.downcase}%").order('title')
  end


  def self.categorize(category)
    where('LOWER(category) = ?', "#{category.downcase}")
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def set_meta(obj=nil)
    @meta_title = 'Puchu Maldito'
    @meta_description = 'I am Puchu-Puchu the stubborn cat. I will share to you my master\'s secrets.'
    @meta_keywords = 'puchu, stubborn, cat, el, gato, maldito, geek'

    case action_name
    when 'search'
      @meta_title = 'Search'
    when 'categorize'
      @meta_title = "#{params[:category].capitalize}"
    when 'show'
      @meta_title = obj.title
      @meta_description = obj.description
      @meta_keywords = obj.tags
    end
  end


  def set_page_title(title='')
    case action_name
    when 'index'
      @page_title = 'Welcome, Gatos!'
    when 'search'
      @page_title = "Search for results for \"#{params[:keyword]}\"."
    when 'show'
      @page_title = title
    end
  end


  def get_categories
    @categories = Post.uniq.pluck(:category).sort
  end


  def get_recents
    @recents = Post.order('id desc').limit(10)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  layout 'application'

  before_action :get_categories, :get_recents
  before_action  :set_meta, :set_page_title, only: [:index, :search, :categorize]
  

  def index
    @posts = Post.order('id desc').paginate(page: params[:page], per_page: 8)
    redirect_to root_path and return if @posts.empty?
    respond_to do |format|
      format.html
      # format.json { render json: @posts.as_json }
    end
  end

  
  def show
    @post = Post.get params[:title]
    if @post.present?
      set_meta @post
      set_page_title @post.title
    else
      redirect_to root_path
    end
  end


  def search
    if params[:keyword].strip.present? 
      render json: Post.select(:title).search(params[:keyword])
    else
      render json: Hash.new
    end
  end


  def categorize
    @members = Post.categorize(params[:category]).paginate(page: params[:page], per_page: 8)
    redirect_to root_path and return if @members.empty?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def activo(category)
    if action_name == "categorize"
      "active" if @members.first.category.downcase == category.downcase
    end
  end


  def search_notify
    count = @candidates.count
    if count > 0
      "#{count} #{'result'.pluralize(count)} found for query \"#{params[:keyword]}\"."
    else
      "0 result for query \"#{params[:keyword]}\"."
    end 
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">

<title><%= @meta_title %></title>

<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="<%= @meta_description %>" />
<meta name="keywords" content="<%= @meta_keywords %>" />

<meta property="fb:admins" content="100008742280813" />
<meta property="og:image" content="<%= request.base_url + '/images/puchu-og-img.png' %>" />
<meta property="og:site_name" content="Puchu Maldito" />

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'partials/header' %>
<%= yield %>
<%= render partial: 'partials/footer' %>

<!-- Google Analytics -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-58475252-2', 'auto');
    ga('send', 'pageview');
</script>

</body>
</html>

app/views/partials/_disqus.html.erb
<script>
    if(typeof DISQUS === "undefined") {
        var disqus_shortname = 'puchumaldito';
        var disqus_identifier =  '<%= created.strftime("%m%d%y%I%M%S") %>';
        var disqus_url =  '<%= request.url %>';

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    } else {
        DISQUS.reset({
            reload: true,
            config: function () {
                this.page.identifier = disqus_identifier;
                this.page.url = disqus_url;
            }
        });
    }
</script>

<noscript>
    Please enable JavaScript to view the 
    <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
</noscript>

app/views/partials/_footer.html.erb
<div class="footer container-fluid no-mg">
    <div class="container">
        <div class="row">
            <div class="img-wrap col-md-5 col-md-offset-3 text-center">
                <a href="https://www.facebook.com/puchupuchumikhail.kalashnikov">
                    <img class="puchu shot all-trans img img-circle" 
                         src="<%= request.base_url + '/images/puchu-mikhail.jpg' %>" 
                         height="124" alt="Puchu Mikhail">
                </a>
            </div>
            <div class="about-me col-md-5 col-md-offset-3 text-center">
                <h4>A bit of Me</h4>
                <p>
                    When my mummy and duddy passed through a garbage dumpsite, <br>they saw me weeping, frightened and cold. They took pity on me, brought me to church and had me baptized. After that, they took me to their home and dressed me to stop chilling.
                </p>
                 
                <p>
                    After a while, I learned Web Development and other Tech stuff. <br>I created this blog for the documentation of my learnings. I did not make this website for you or for anybody else, just for my own memory. 
                </p>

                <p>
                    So, if you have any violent reaction, <br>keep it to yourself <br>'cause I don't give a Damn.
                </p>
                 
                <h5 style="color:orange">Viva El Gatos!</h5>
            </div>
        </div>
    </div>
</div>

app/views/partials/_header.html.erb
<nav class="header navbar navbar-inverse navbar-static-top" id="top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" 
                    class="navbar-toggle collapsed all-trans" 
                    data-toggle="collapse" 
                    data-target="#navbar-collapse-items">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand color-trans" href="<%= root_path %>" style="font-family: 'Rock Salt'">
                Puchu Maldito
            </a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-items">
            <% if action_name != "show" %>
                <ul class="nav navbar-nav">
                    <% @categories.each do |category| %>
                        <li>
                            <a class="<%= activo category %> color-trans" href="<%= categorize_path(category.downcase) %>">
                                <%= category %>
                            </a>
                        </li>
                    <% end %>
                </ul>
            <% end %>
            <% if action_name == "show" %>
                <ul class="social-share nav navbar-nav">
                    <li>
                        <a class="color-trans" 
                           href="https://twitter.com/share"
                           data-url="<%= request.url %>" 
                           target="_blank">
                            tweet &nbsp;<i class="fa fa-twitter fa-lg"></i>
                        </a>
                    </li>
                    <li>
                        <a class="color-trans" 
                           href="https://plus.google.com/share?url=<%= request.url %>"
                           target="_blank">
                            share &nbsp;<i class="fa fa-google-plus fa-lg"></i>
                        </a>
                    </li>
                    <li>
                        <a class="color-trans" 
                           href="http://pinterest.com/pin/create/link/?url=<%= request.url %>"
                           target="_blank">
                            pin it! &nbsp;<i class="fa fa-pinterest fa-lg"></i>
                        </a>
                    </li>
                    <li>
                        <a class="color-trans" 
                           href="https://www.facebook.com/sharer/sharer.php?u=<%= request.url %>"
                           target="_blank">
                            share &nbsp;<i class="fa fa-facebook fa-lg"></i>
                        </a>
                    </li>
                </ul>
            <% end %>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a 
                        class="color-trans" 
                        id="launch-se" 
                        href="javascript:void(0);">
                        <i class="fa fa-search fa-lg"></i>
                    </a>
                </li>
            </ul>
        </div> <!-- end of navbar-collapse-items -->       
    </div>
</nav>

<div class="modal fade" id="modal-search">
    <div class="modal-dialog">
        <div class="search-mismo col-md-12" style="margin-top:100px;">
            <form accept-charset="UTF-8" 
                  name="form-se"
                  role="search"
                  method="GET">
                <input name="utf8" type="hidden" value="&#x2713;">
                <div class="form-group has-warning">
                    <input name="keyword" 
                           type="text" 
                           class="form-control input-block"
                           placeholder="Search..."
                           autocomplete="off"
                           maxlength="30" 
                           required>
                    <i class="fa fa-search fa-lg"></i>
                </div>
                <div class="candidates"></div>
            </form>
        </div>
    </div>
</div>

app/views/partials/_sidebar.html.erb
<!--<div class="panel panel-default dark animated bounceInRight">
    <div class="panel-body text-center">
        <img src="/puchu-mikhail.png">
        <ul class="list-inline y-offset-10 no-mgb">
            <li>follow me: </li>
            <li><a href="https://twitter.com/PuchuMikhail" href="_blank"><i class="fa fa-twitter-square fa-lg"></i></a></li>
            <li><a href="https://www.facebook.com/puchupuchumikhail.kalashnikov" target="_blank"><i class="fa fa-facebook-square fa-lg"></i></a></li>
        </ul>
    </div>
</div>-->
<div class="panel panel-default dark animated bounceInRight">
    <div class="panel-body">
        <%= form_tag search_path, method: 'get', role: 'search' do %>
                <%= search_field_tag 'keyword', 
                        params[:keyword], 
                        placeholder: 'secret finder', 
                        maxlength: 20,
                        autocomplete: :off,
                        class: 'form-control input-sm input-block' %>
                <i class="fa fa-search fa-flip-horizontal"></i>
        <% end %>
    </div>
</div>
<div class="panel panel-default dark animated bounceInRight">
    <div class="panel-body">
        <span class="list-headers">Categories</span>
        <ul class="list-unstyled">
            <% @categories.each do |category| %>
            <li class="list-items"><a href="<%= categorize_path(category.downcase) %>"><%= category %></a></li>
            <% end %>
        </ul>
    </div>
</div>
<div class="panel panel-default dark animated bounceInRight">
    <div class="panel-body">
        <span class="list-headers">Recently Revealed</span>
        <ul class="list-unstyled">
            <% @recents.each do |recent| %>
            <li class="list-items">
                <a href="<%= detailed_path(recent.title.parameterize) %>">
                    <%= recent.title %>
                </a>
            </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/partials/_socialmediashare.html.erb
<div class="wrap-share">
    <ul class="list-inline">
        <li><strong>SHARE THIS ON :</strong></li>
        <li>
            <a href="javascript:void(0);">
                <i class="fa fa-twitter-square fa-lg"></i>
            </a>
        </li>
        <li>
            <a href="javascript:void(0);">
                <i class="fa fa-google-plus-square fa-lg"></i>
            </a>
        </li>
        <li>
            <a class="fb-share" href="javascript:void(0);">
                <i class="fa fa-facebook-square fa-lg"></i>
            </a>
        </li>
    </ul>
</div>

app/views/partials/_top_scroll.html.erb
<div class="top-scroll wow fadeInDown">
    <a class="all-trans" href="#top">
        <i class="fa fa-angle-double-down fa-2x"></i>
    </a>
</div>

app/views/partials/_topbar.html.erb
<div class="panel panel-default top-bar dark animated bounceInDown">
    <div class="panel-body">
        <a class="pull-left" href="/">
            <i class="fa fa-home fa-2x"></i>
            <strong class="hidden-xs">&nbsp;Home</strong>
        </a>
        <a class="pull-right" href="<%= posts_path %>.json" target="_blank">
            <strong class="hidden-xs">API&nbsp;</strong>
            <i class="fa fa-paw fa-2x"></i>
        </a>
    </div>
</div>

app/views/posts/categorize.html.erb
<div class="categorized container-fluid">
    <div class="container">
        <div class="row animated bounceInDown">
            <div class="col-lg-8">
                <div class="alert alert-info">
                    articles under <%= params[:category].titleize %> category.
                </div>
            </div>
        </div>
        <div class="row content">
            <div class="col-lg-8">
                <% @members.each do |member| %>
                    <a class="post-item color-trans" href="<%= detailed_path(member.title.parameterize) %>">
                        <h3><%= member.title %></h3>
                        <p><%= member.description %></p>
                    </a>
                <% end %>
                <div class="page-wrap y-offset-50">
                    <%= will_paginate @members %>
                </div>
            </div>
        </div>
        <%= render partial: 'partials/top_scroll' %>
    </div>
</div>

app/views/posts/index.html.erb
<div class="index container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 content">
                <% @posts.each do |post| %>
                    <a class="post-item all-trans" href="<%= detailed_path(post.title.parameterize) %>">
                        <h3><%= post.title %></h3>
                        <p><%= post.description %></p>
                    </a>
                <% end %>
                <div class="page-wrap y-offset-50">
                    <%= will_paginate @posts %>
                </div>
            </div>
        </div>
        <%= render partial: 'partials/top_scroll' %>
    </div>
</div>

app/views/posts/search.html.erb
<div class="search container-fluid">
    <div class="container">
        <div class="row animated bounceInDown">
            <div class="col-lg-8">
                <div class="alert alert-info">
                    <%= search_notify %>
                </div>
            </div>
        </div>
        <div class="row content">
            <div class="col-lg-8">
                <% @candidates.each do |candidate| %>
                    <a class="post-item color-trans" href="<%= detailed_path(candidate.title.parameterize) %>">
                        <h3><%= candidate.title %></h3>
                        <p><%= candidate.description %></p>
                    </a>
                <% end %>
            </div>
        </div>
        <%= render partial: 'partials/top_scroll' %>
    </div>
</div>

app/views/posts/show.html.erb
<div class="show container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 content">
                <h1 class="page-header"><%= @post.title %></h1>
                <%= @post.content.html_safe %>
                
                <!-- disqus comment box -->
        		<div id="disqus_thread" class="y-offset-50"></div>
            </div>
        </div>
        <%= render partial: 'partials/top_scroll' %>
    </div>
</div>
<!-- initialize disqus -->
<%= render partial: 'partials/disqus', locals: { created: @post.created_at } %>